language: clojure
lein: 2.7.1
install:
  - (cd; git clone https://github.com/divergentdave/eastwood.git; cd eastwood; git checkout for-tenforty; lein install)
  - (cd; git clone https://github.com/divergentdave/kibit.git; cd kibit; git checkout allow-reader-conditionals; cd kibit; lein install; cd ../lein-kibit; lein install)
  - echo '{:user {:plugins [[jonase/eastwood "0.2.4-SNAPSHOT"][lein-kibit "0.1.4-SNAPSHOT"]]}}' > ~/.lein/profiles.clj
  - lein with-profile +dev deps
script:
  - lein with-profile +dev cljfmt check
  - lein eastwood
  - lein kibit
  - lein test
  - lein cljsbuild once dev
  - lein cljsbuild once test
  - lein cljsbuild test
